import { storage } from "./storage";
import type { InsertStockMaster } from "@shared/schema";

// 한국 증시 주요 종목 데이터 (실제 데이터 기반)
const koreaStocks: InsertStockMaster[] = [
  // 대형주 (시가총액 10조 이상)
  {
    stockCode: "005930",
    stockName: "삼성전자",
    stockNameEng: "Samsung Electronics",
    market: "KOSPI",
    sector: "전기전자",
    industry: "반도체",
    marketCap: "400000000000000",
    isActive: true,
  },
  {
    stockCode: "373220",
    stockName: "LG에너지솔루션",
    stockNameEng: "LG Energy Solution",
    market: "KOSPI",
    sector: "전기전자",
    industry: "배터리",
    marketCap: "100000000000000",
    isActive: true,
  },
  {
    stockCode: "207940",
    stockName: "삼성바이오로직스",
    stockNameEng: "Samsung Biologics",
    market: "KOSPI",
    sector: "의료정밀",
    industry: "바이오의약품",
    marketCap: "70000000000000",
    isActive: true,
  },
  {
    stockCode: "000660",
    stockName: "SK하이닉스",
    stockNameEng: "SK Hynix",
    market: "KOSPI",
    sector: "전기전자",
    industry: "반도체",
    marketCap: "65000000000000",
    isActive: true,
  },
  {
    stockCode: "035420",
    stockName: "NAVER",
    stockNameEng: "NAVER",
    market: "KOSPI",
    sector: "서비스업",
    industry: "인터넷",
    marketCap: "45000000000000",
    isActive: true,
  },

  // 중형주 (시가총액 1조~10조)
  {
    stockCode: "035720",
    stockName: "카카오",
    stockNameEng: "Kakao",
    market: "KOSPI",
    sector: "서비스업",
    industry: "인터넷",
    marketCap: "25000000000000",
    isActive: true,
  },
  {
    stockCode: "003670",
    stockName: "포스코홀딩스",
    stockNameEng: "POSCO Holdings",
    market: "KOSPI",
    sector: "철강금속",
    industry: "철강",
    marketCap: "20000000000000",
    isActive: true,
  },
  {
    stockCode: "096770",
    stockName: "SK이노베이션",
    stockNameEng: "SK Innovation",
    market: "KOSPI",
    sector: "화학",
    industry: "정유",
    marketCap: "18000000000000",
    isActive: true,
  },
  {
    stockCode: "323410",
    stockName: "카카오뱅크",
    stockNameEng: "KakaoBank",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "15000000000000",
    isActive: true,
  },
  {
    stockCode: "017670",
    stockName: "SK텔레콤",
    stockNameEng: "SK Telecom",
    market: "KOSPI",
    sector: "통신업",
    industry: "통신서비스",
    marketCap: "12000000000000",
    isActive: true,
  },

  // 소형주 및 성장주
  {
    stockCode: "091990",
    stockName: "셀트리온헬스케어",
    stockNameEng: "Celltrion Healthcare",
    market: "KOSPI",
    sector: "의료정밀",
    industry: "바이오의약품",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "068270",
    stockName: "셀트리온",
    stockNameEng: "Celltrion",
    market: "KOSPI",
    sector: "의료정밀",
    industry: "바이오의약품",
    marketCap: "7000000000000",
    isActive: true,
  },
  {
    stockCode: "012330",
    stockName: "현대모비스",
    stockNameEng: "Hyundai Mobis",
    market: "KOSPI",
    sector: "운수장비",
    industry: "자동차부품",
    marketCap: "6000000000000",
    isActive: true,
  },
  {
    stockCode: "000270",
    stockName: "기아",
    stockNameEng: "Kia",
    market: "KOSPI",
    sector: "운수장비",
    industry: "자동차",
    marketCap: "5500000000000",
    isActive: true,
  },
  {
    stockCode: "005380",
    stockName: "현대차",
    stockNameEng: "Hyundai Motor",
    market: "KOSPI",
    sector: "운수장비",
    industry: "자동차",
    marketCap: "5000000000000",
    isActive: true,
  },

  // KOSDAQ 대표 종목
  {
    stockCode: "347860",
    stockName: "알테오젠",
    stockNameEng: "Alteogen",
    market: "KOSDAQ",
    sector: "의료정밀",
    industry: "바이오의약품",
    marketCap: "4000000000000",
    isActive: true,
  },
  {
    stockCode: "277810",
    stockName: "레인보우로보틱스",
    stockNameEng: "Rainbow Robotics",
    market: "KOSDAQ",
    sector: "기계",
    industry: "로봇",
    marketCap: "3500000000000",
    isActive: true,
  },
  {
    stockCode: "039490",
    stockName: "키움증권",
    stockNameEng: "Kiwoom Securities",
    market: "KOSDAQ",
    sector: "금융업",
    industry: "증권",
    marketCap: "3000000000000",
    isActive: true,
  },
  {
    stockCode: "263750",
    stockName: "펄어비스",
    stockNameEng: "Pearl Abyss",
    market: "KOSDAQ",
    sector: "서비스업",
    industry: "게임",
    marketCap: "2500000000000",
    isActive: true,
  },
  {
    stockCode: "259960",
    stockName: "크래프톤",
    stockNameEng: "Krafton",
    market: "KOSDAQ",
    sector: "서비스업",
    industry: "게임",
    marketCap: "2000000000000",
    isActive: true,
  },

  // 추가 주요 종목
  {
    stockCode: "051910",
    stockName: "LG화학",
    stockNameEng: "LG Chem",
    market: "KOSPI",
    sector: "화학",
    industry: "화학",
    marketCap: "45000000000000",
    isActive: true,
  },
  {
    stockCode: "028260",
    stockName: "삼성물산",
    stockNameEng: "Samsung C&T",
    market: "KOSPI",
    sector: "건설업",
    industry: "건설",
    marketCap: "18000000000000",
    isActive: true,
  },
  {
    stockCode: "066570",
    stockName: "LG전자",
    stockNameEng: "LG Electronics",
    market: "KOSPI",
    sector: "전기전자",
    industry: "가전",
    marketCap: "25000000000000",
    isActive: true,
  },
  {
    stockCode: "032640",
    stockName: "LG유플러스",
    stockNameEng: "LG Uplus",
    market: "KOSPI",
    sector: "통신업",
    industry: "통신서비스",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "018260",
    stockName: "삼성에스디에스",
    stockNameEng: "Samsung SDS",
    market: "KOSPI",
    sector: "서비스업",
    industry: "IT서비스",
    marketCap: "12000000000000",
    isActive: true,
  },
  {
    stockCode: "034730",
    stockName: "SK",
    stockNameEng: "SK",
    market: "KOSPI",
    sector: "기타",
    industry: "지주회사",
    marketCap: "22000000000000",
    isActive: true,
  },
  {
    stockCode: "005490",
    stockName: "POSCO홀딩스",
    stockNameEng: "POSCO Holdings",
    market: "KOSPI",
    sector: "철강금속",
    industry: "철강",
    marketCap: "20000000000000",
    isActive: true,
  },
  {
    stockCode: "015760",
    stockName: "한국전력",
    stockNameEng: "Korea Electric Power",
    market: "KOSPI",
    sector: "전기가스업",
    industry: "전력",
    marketCap: "15000000000000",
    isActive: true,
  },
  {
    stockCode: "033780",
    stockName: "KT&G",
    stockNameEng: "KT&G",
    market: "KOSPI",
    sector: "음식료품",
    industry: "담배",
    marketCap: "10000000000000",
    isActive: true,
  },
  {
    stockCode: "030200",
    stockName: "KT",
    stockNameEng: "KT",
    market: "KOSPI",
    sector: "통신업",
    industry: "통신서비스",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "105560",
    stockName: "KB금융",
    stockNameEng: "KB Financial Group",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "20000000000000",
    isActive: true,
  },
  {
    stockCode: "055550",
    stockName: "신한지주",
    stockNameEng: "Shinhan Financial Group",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "18000000000000",
    isActive: true,
  },
  {
    stockCode: "086790",
    stockName: "하나금융지주",
    stockNameEng: "Hana Financial Group",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "15000000000000",
    isActive: true,
  },
  {
    stockCode: "316140",
    stockName: "우리금융지주",
    stockNameEng: "Woori Financial Group",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "12000000000000",
    isActive: true,
  },
  {
    stockCode: "024110",
    stockName: "기업은행",
    stockNameEng: "Industrial Bank of Korea",
    market: "KOSPI",
    sector: "금융업",
    industry: "은행",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "009150",
    stockName: "삼성전기",
    stockNameEng: "Samsung Electro-Mechanics",
    market: "KOSPI",
    sector: "전기전자",
    industry: "전자부품",
    marketCap: "15000000000000",
    isActive: true,
  },
  {
    stockCode: "000810",
    stockName: "삼성화재",
    stockNameEng: "Samsung Fire & Marine Insurance",
    market: "KOSPI",
    sector: "금융업",
    industry: "보험",
    marketCap: "12000000000000",
    isActive: true,
  },
  {
    stockCode: "032830",
    stockName: "삼성생명",
    stockNameEng: "Samsung Life Insurance",
    market: "KOSPI",
    sector: "금융업",
    industry: "보험",
    marketCap: "10000000000000",
    isActive: true,
  },
  {
    stockCode: "138040",
    stockName: "메리츠금융지주",
    stockNameEng: "Meritz Financial Group",
    market: "KOSPI",
    sector: "금융업",
    industry: "보험",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "047050",
    stockName: "포스코인터내셔널",
    stockNameEng: "POSCO International",
    market: "KOSPI",
    sector: "유통업",
    industry: "종합상사",
    marketCap: "5000000000000",
    isActive: true,
  },

  // 신재생에너지 및 ESG 관련 종목
  {
    stockCode: "267260",
    stockName: "HD현대일렉트릭",
    stockNameEng: "HD Hyundai Electric",
    market: "KOSPI",
    sector: "전기전자",
    industry: "전력장비",
    marketCap: "4000000000000",
    isActive: true,
  },
  {
    stockCode: "329180",
    stockName: "HD현대중공업",
    stockNameEng: "HD Hyundai Heavy Industries",
    market: "KOSPI",
    sector: "조선",
    industry: "조선",
    marketCap: "25000000000000",
    isActive: true,
  },
  {
    stockCode: "010950",
    stockName: "S-Oil",
    stockNameEng: "S-Oil",
    market: "KOSPI",
    sector: "화학",
    industry: "정유",
    marketCap: "12000000000000",
    isActive: true,
  },
  {
    stockCode: "011780",
    stockName: "금호석유",
    stockNameEng: "Kumho Petrochemical",
    market: "KOSPI",
    sector: "화학",
    industry: "화학",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "010130",
    stockName: "고려아연",
    stockNameEng: "Korea Zinc",
    market: "KOSPI",
    sector: "철강금속",
    industry: "비철금속",
    marketCap: "10000000000000",
    isActive: true,
  },
  {
    stockCode: "005830",
    stockName: "DB손해보험",
    stockNameEng: "DB Insurance",
    market: "KOSPI",
    sector: "금융업",
    industry: "보험",
    marketCap: "6000000000000",
    isActive: true,
  },
  {
    stockCode: "361610",
    stockName: "SK아이이테크놀로지",
    stockNameEng: "SK ie technology",
    market: "KOSPI",
    sector: "전기전자",
    industry: "배터리소재",
    marketCap: "15000000000000",
    isActive: true,
  },
  {
    stockCode: "326030",
    stockName: "SK바이오팜",
    stockNameEng: "SK Biopharmaceuticals",
    market: "KOSPI",
    sector: "의료정밀",
    industry: "바이오의약품",
    marketCap: "8000000000000",
    isActive: true,
  },
  {
    stockCode: "003550",
    stockName: "LG",
    stockNameEng: "LG",
    market: "KOSPI",
    sector: "기타",
    industry: "지주회사",
    marketCap: "12000000000000",
    isActive: true,
  },
  {
    stockCode: "272210",
    stockName: "한화시스템",
    stockNameEng: "Hanwha Systems",
    market: "KOSPI",
    sector: "전기전자",
    industry: "방산",
    marketCap: "4000000000000",
    isActive: true,
  },
];

export async function seedStockData() {
  console.log("🌱 한국 주요 종목 데이터 시드 시작...");
  
  try {
    let insertedCount = 0;
    let updatedCount = 0;
    
    for (const stock of koreaStocks) {
      try {
        const result = await storage.upsertStockMaster(stock);
        if (result) {
          console.log(`✅ ${stock.stockName} (${stock.stockCode}) 처리 완료`);
          insertedCount++;
        }
      } catch (error) {
        console.error(`❌ ${stock.stockName} (${stock.stockCode}) 처리 실패:`, error);
      }
    }
    
    console.log(`🎉 종목 데이터 시드 완료! 총 ${insertedCount}개 종목 처리`);
    
    // 전체 종목 수 확인
    const allStocks = await storage.getAllStocks();
    console.log(`📊 현재 데이터베이스에 등록된 활성 종목 수: ${allStocks.length}개`);
    
  } catch (error) {
    console.error("💥 종목 데이터 시드 실패:", error);
    throw error;
  }
}

// 직접 실행시 시드 실행
if (import.meta.url === `file://${process.argv[1]}`) {
  seedStockData()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}